use_frameworks!

platform :ios, '12.0'

target 'EZLinksSDK_Example' do
  pod 'EZLinksSDK', :path => '../'
  pod 'Alamofire', '~> 5.6'
  target 'EZLinksSDK_Tests' do
    inherit! :search_paths

    
  end
end
